name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]

    steps:
      - if: matrix.os == 'windows'
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
          use-cache: false

      - run: zig build test -freference-trace --summary all